from pathlib import Path


def replace(path, old, new, count=1):
    p = Path(path)
    text = p.read_text(encoding='utf-8')
    if old not in text:
        raise SystemExit(f'missing pattern in {path}: {old[:120]}')
    text = text.replace(old, new, count)
    p.write_text(text, encoding='utf-8')


p = Path('news_service_v37.py')
text = p.read_text(encoding='utf-8')

old = '''KR_EVENT_WORDS = (\n    "실적", "영업이익", "매출", "수주", "계약", "인수", "합병", "증자", "감자",\n    "배당", "자사주", "공시", "승인", "소송", "리콜", "목표가", "투자의견",\n)\nUS_EVENT_WORDS = (\n    "earnings", "revenue", "guidance", "acquire", "acquisition", "merger", "buyback",\n    "dividend", "offering", "sec", "fda", "lawsuit", "recall", "forecast", "upgrade", "downgrade",\n)\n'''
new = '''MIN_HIGHLIGHT_INVESTMENT_SCORE = 18.0\n\n# Home TOP news is investor-first: market-moving business events outrank simple company mentions.\nKR_INVESTMENT_CATEGORIES = (\n    ("earnings", 50, ("실적", "영업이익", "영업손실", "순이익", "순손실", "매출", "흑자전환", "적자전환", "어닝", "가이던스", "실적 전망")),\n    ("orders", 42, ("수주", "공급계약", "계약 체결", "납품", "고객사", "발주", "수주잔고")),\n    ("capital", 38, ("배당", "자사주", "증자", "감자", "유상증자", "무상증자", "회사채", "차입", "신용등급", "분할", "상장")),\n    ("strategy", 34, ("인수", "합병", "m&a", "매각", "지분 인수", "투자", "증설", "감산", "생산능력", "capex", "공장", "라인 가동")),\n    ("technology", 30, ("파운드리", "hbm", "dram", "낸드", "반도체", "2나노", "3나노", "공정", "수율", "양산", "출하", "신제품", "출시", "점유율")),\n    ("analyst", 28, ("목표가", "목표주가", "투자의견", "매수", "매도", "상향", "하향", "컨센서스")),\n    ("market", 26, ("주가", "급등", "급락", "외국인", "기관", "수급", "공매도", "거래량")),\n    ("policy", 28, ("공시", "승인", "규제", "관세", "보조금", "소송", "리콜", "제재", "조사", "과징금")),\n    ("pricing", 26, ("가격 인상", "가격 인하", "판가", "가격 상승", "가격 하락", "판매량", "출하량")),\n)\nUS_INVESTMENT_CATEGORIES = (\n    ("earnings", 50, ("earnings", "revenue", "profit", "loss", "eps", "guidance", "forecast", "outlook", "margin")),\n    ("orders", 42, ("contract", "order", "supply deal", "customer", "backlog", "shipment")),\n    ("capital", 38, ("dividend", "buyback", "offering", "debt", "bond", "credit rating", "split", "ipo")),\n    ("strategy", 34, ("acquire", "acquisition", "merger", "m&a", "sell stake", "investment", "capex", "capacity", "factory", "fab")),\n    ("technology", 30, ("foundry", "hbm", "dram", "nand", "semiconductor", "2nm", "3nm", "yield", "mass production", "launch", "market share")),\n    ("analyst", 28, ("price target", "upgrade", "downgrade", "rating", "buy", "sell", "outperform", "underperform")),\n    ("market", 26, ("shares", "stock", "surge", "plunge", "short interest", "volume")),\n    ("policy", 28, ("sec", "fda", "approval", "regulation", "tariff", "subsidy", "lawsuit", "recall", "probe", "fine")),\n    ("pricing", 26, ("price increase", "price cut", "pricing", "unit sales", "shipments")),\n)\nKR_LOW_VALUE_WORDS = (\n    "어린이", "청소년", "교육", "사용법", "캠페인", "봉사", "기부", "사회공헌", "후원",\n    "공모전", "체험", "축제", "문화행사", "지역사회", "장학", "취약계층", "홍보대사", "나눔",\n)\nUS_LOW_VALUE_WORDS = (\n    "children", "students", "education", "how to use", "campaign", "volunteer", "donation",\n    "charity", "sponsorship", "contest", "festival", "community event", "scholarship", "ambassador",\n)\n'''
if old not in text:
    raise SystemExit('event constants block missing')
text = text.replace(old, new, 1)

old = '''def _news_score(title: str, published_ts: float, market: str, name: str, symbol: str) -> float:\n    now = time.time()\n    age_hours = max(0.0, (now - published_ts) / 3600) if published_ts else 240.0\n    score = max(0.0, 120.0 - age_hours * 2.0)\n    lowered = title.lower()\n    words = KR_EVENT_WORDS if market == "KR" else US_EVENT_WORDS\n    score += sum(12 for word in words if word.lower() in lowered)\n    if name and name.lower() in lowered:\n        score += 20\n    bare = symbol.split(".")[0].lower()\n    if bare and bare in lowered:\n        score += 10\n    return round(score, 2)\n'''
new = '''def _investment_relevance(title: str, context: str, market: str) -> tuple[float, list[str]]:\n    text = f"{title} {context}".lower()\n    categories = KR_INVESTMENT_CATEGORIES if market == "KR" else US_INVESTMENT_CATEGORIES\n    low_value_words = KR_LOW_VALUE_WORDS if market == "KR" else US_LOW_VALUE_WORDS\n\n    score = 0.0\n    tags: list[str] = []\n    for tag, weight, words in categories:\n        if any(word.lower() in text for word in words):\n            score += float(weight)\n            tags.append(tag)\n\n    low_hits = sum(1 for word in low_value_words if word.lower() in text)\n    if low_hits:\n        # CSR/education/event stories should not become Home TOP news merely because they are fresh.\n        score -= (60.0 + max(0, low_hits - 1) * 12.0) if not tags else low_hits * 22.0\n\n    if tags and re.search(r"\\d+(?:\\.\\d+)?\\s*(?:%|조|억|만|달러|원|billion|million|bn|mn)", text, re.I):\n        score += 8.0\n    return round(score, 2), tags\n\n\ndef _news_score(title: str, published_ts: float, market: str, name: str, symbol: str, context: str = "") -> float:\n    now = time.time()\n    age_hours = max(0.0, (now - published_ts) / 3600) if published_ts else 240.0\n    # Recency matters, but it must never dominate actual investment relevance.\n    recency_score = max(0.0, 30.0 - age_hours * 0.625)\n    investment_score, _ = _investment_relevance(title, context, market)\n    score = investment_score + recency_score\n    lowered = title.lower()\n    if name and name.lower() in lowered:\n        score += 10.0\n    bare = symbol.split(".")[0].lower()\n    if bare and bare in lowered:\n        score += 6.0\n    if investment_score < MIN_HIGHLIGHT_INVESTMENT_SCORE:\n        score -= 35.0\n    return round(score, 2)\n'''
if old not in text:
    raise SystemExit('news score function missing')
text = text.replace(old, new, 1)

old = '''def _balanced_highlights(items: list[dict], limit: int = 12) -> list[dict]:\n    """Keep relevance while preventing one active ticker from monopolizing Home highlights."""\n    ranked = _dedupe(items)\n    if not ranked or limit <= 0:\n        return []\n\n    first_by_symbol: dict[str, dict] = {}\n    for row in ranked:\n        symbol = str(row.get("symbol") or "").upper()\n        if symbol and symbol not in first_by_symbol:\n            first_by_symbol[symbol] = row\n\n    primary = sorted(\n        first_by_symbol.values(),\n        key=lambda x: (-float(x.get("score") or 0), -float(x.get("publishedTs") or 0)),\n    )\n    chosen = primary[:limit]\n    chosen_ids = {(str(row.get("url") or ""), str(row.get("title") or "")) for row in chosen}\n    if len(chosen) < limit:\n        for row in ranked:\n            identity = (str(row.get("url") or ""), str(row.get("title") or ""))\n            if identity in chosen_ids:\n                continue\n            chosen.append(row)\n            chosen_ids.add(identity)\n            if len(chosen) >= limit:\n                break\n    return chosen\n'''
new = '''def _balanced_highlights(items: list[dict], limit: int = 12) -> list[dict]:\n    """Investor-first Home highlights with ticker diversity; low-value company mentions are omitted."""\n    ranked = _dedupe(items)\n    if not ranked or limit <= 0:\n        return []\n\n    qualified = [\n        row for row in ranked\n        if "investmentRelevant" not in row or bool(row.get("investmentRelevant"))\n    ]\n    if not qualified:\n        return []\n\n    first_by_symbol: dict[str, dict] = {}\n    for row in qualified:\n        symbol = str(row.get("symbol") or "").upper()\n        if symbol and symbol not in first_by_symbol:\n            first_by_symbol[symbol] = row\n\n    primary = sorted(\n        first_by_symbol.values(),\n        key=lambda x: (-float(x.get("score") or 0), -float(x.get("publishedTs") or 0)),\n    )\n    chosen = primary[:limit]\n    chosen_ids = {(str(row.get("url") or ""), str(row.get("title") or "")) for row in chosen}\n    if len(chosen) < limit:\n        for row in qualified:\n            identity = (str(row.get("url") or ""), str(row.get("title") or ""))\n            if identity in chosen_ids:\n                continue\n            chosen.append(row)\n            chosen_ids.add(identity)\n            if len(chosen) >= limit:\n                break\n    return chosen\n'''
if old not in text:
    raise SystemExit('balanced highlights function missing')
text = text.replace(old, new, 1)

old = '''        items.append({\n            "symbol": symbol,\n            "name": name or symbol,\n            "market": "KR",\n            "title": title,\n            "source": _host_label(url),\n            "publishedAt": published_at,\n            "publishedTs": published_ts,\n            "url": url,\n            "provider": "NAVER API HUB",\n            "score": _news_score(title, published_ts, "KR", name, symbol),\n        })\n'''
new = '''        context = _clean_text(raw.get("description"))\n        investment_score, investment_tags = _investment_relevance(title, context, "KR")\n        items.append({\n            "symbol": symbol,\n            "name": name or symbol,\n            "market": "KR",\n            "title": title,\n            "source": _host_label(url),\n            "publishedAt": published_at,\n            "publishedTs": published_ts,\n            "url": url,\n            "provider": "NAVER API HUB",\n            "score": _news_score(title, published_ts, "KR", name, symbol, context),\n            "investmentScore": investment_score,\n            "investmentRelevant": investment_score >= MIN_HIGHLIGHT_INVESTMENT_SCORE,\n            "investmentTags": investment_tags,\n        })\n'''
if old not in text:
    raise SystemExit('naver item block missing')
text = text.replace(old, new, 1)

old = '''        items.append({\n            "symbol": symbol,\n            "name": name or symbol,\n            "market": "US",\n            "title": title,\n            "source": source,\n            "publishedAt": published_at,\n            "publishedTs": published_ts,\n            "url": url,\n            "provider": "Finnhub",\n            "score": _news_score(title, published_ts, "US", name, symbol),\n        })\n'''
new = '''        context = _clean_text(raw.get("summary"))\n        investment_score, investment_tags = _investment_relevance(title, context, "US")\n        items.append({\n            "symbol": symbol,\n            "name": name or symbol,\n            "market": "US",\n            "title": title,\n            "source": source,\n            "publishedAt": published_at,\n            "publishedTs": published_ts,\n            "url": url,\n            "provider": "Finnhub",\n            "score": _news_score(title, published_ts, "US", name, symbol, context),\n            "investmentScore": investment_score,\n            "investmentRelevant": investment_score >= MIN_HIGHLIGHT_INVESTMENT_SCORE,\n            "investmentTags": investment_tags,\n        })\n'''
if old not in text:
    raise SystemExit('finnhub item block missing')
text = text.replace(old, new, 1)

text = text.replace('''        "displayPolicy": "headline-source-time-link-only",\n        "notice": "기사 본문과 이미지는 저장·재게시하지 않고 원문 링크로 연결합니다.",\n''', '''        "displayPolicy": "headline-source-time-link-only",\n        "selectionPolicy": "investor-first-diverse-v41.6",\n        "notice": "기사 본문과 이미지는 저장·재게시하지 않고 원문 링크로 연결합니다.",\n''', 1)
p.write_text(text, encoding='utf-8')

# Add focused regression tests.
t = Path('tests/test_v37_personalized_news.py')
txt = t.read_text(encoding='utf-8')
needle = '''def test_news_dedupe_prefers_higher_scored_duplicate():\n'''
if needle not in txt:
    raise SystemExit('test insertion point missing')
insert = '''def test_investor_ranking_rejects_csr_noise_and_prefers_market_moving_news():\n    now = __import__("time").time()\n    material_title = "삼성전자 2나노 파운드리 대형 수주…생산라인 증설 검토"\n    noise_title = "삼성전자, 어린이에게 AI 사용법 알려준다"\n    material_context = "신규 고객사 공급계약과 생산능력 확대가 예상된다"\n    noise_context = "청소년 대상 교육 캠페인과 체험 행사를 진행한다"\n\n    material_inv, material_tags = news._investment_relevance(material_title, material_context, "KR")\n    noise_inv, noise_tags = news._investment_relevance(noise_title, noise_context, "KR")\n    material_score = news._news_score(material_title, now - 7200, "KR", "삼성전자", "005930.KS", material_context)\n    noise_score = news._news_score(noise_title, now - 60, "KR", "삼성전자", "005930.KS", noise_context)\n\n    assert material_inv >= news.MIN_HIGHLIGHT_INVESTMENT_SCORE\n    assert "orders" in material_tags or "technology" in material_tags\n    assert noise_inv < news.MIN_HIGHLIGHT_INVESTMENT_SCORE\n    assert not noise_tags\n    assert material_score > noise_score + 50\n\n\ndef test_home_highlights_omit_non_investment_company_mentions():\n    rows = [\n        {"symbol": "005930.KS", "title": "삼성전자 어린이 AI 교육", "url": "https://example.com/noise", "score": 90, "publishedTs": 100, "investmentRelevant": False},\n        {"symbol": "000660.KS", "title": "SK하이닉스 HBM 공급 확대", "url": "https://example.com/hbm", "score": 80, "publishedTs": 90, "investmentRelevant": True},\n    ]\n    highlights = news._balanced_highlights(rows, 3)\n    assert [row["symbol"] for row in highlights] == ["000660.KS"]\n\n\n'''
txt = txt.replace(needle, insert + needle, 1)
t.write_text(txt, encoding='utf-8')

assert 'investor-first-diverse-v41.6' in p.read_text(encoding='utf-8')
print('V41.6 investor-first news ranking applied')
