"""Build deterministic release bundles from the legacy asset loaders."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LOADERS = (
    ROOT / "static/js/ux_patch.js",
    ROOT / "static/js/ux_v3.js",
    ROOT / "static/js/home_watchlist_boot_v32c.js",
)
EXTRA_ASSETS = (
    ROOT / "static/css/home_brief_v8.css",
    ROOT / "static/js/home_brief_v8.js",
)
ASSET_CALL = re.compile(
    r"(?:ensureStyle|ensureScript|addStyle|addScript)\(\s*'[^']+'\s*,\s*'(?P<path>/static/(?:css|js)/[^'?]+)(?:\?[^']*)?'"
)


def discover_assets() -> tuple[list[Path], list[Path]]:
    styles: list[Path] = []
    scripts: list[Path] = []
    seen: set[Path] = set()
    for loader in LOADERS:
        for match in ASSET_CALL.finditer(loader.read_text(encoding="utf-8")):
            path = ROOT / match.group("path").lstrip("/")
            if path in seen:
                continue
            seen.add(path)
            (styles if path.suffix == ".css" else scripts).append(path)
    for path in EXTRA_ASSETS:
        if path not in seen:
            (styles if path.suffix == ".css" else scripts).append(path)
    return styles, scripts


def render(paths: list[Path], kind: str) -> str:
    chunks = [f"/* ChartView {kind} bundle. Generated by scripts/build_frontend_bundle.py. */"]
    if kind == "JavaScript":
        chunks.append("window.__CHARTVIEW_RELEASE_BUNDLE__ = true;")
    for path in paths:
        relative = path.relative_to(ROOT).as_posix()
        chunks.append(f"\n/* --- {relative} --- */\n{path.read_text(encoding='utf-8').rstrip()}")
        if kind == "JavaScript":
            chunks.append(";")
    return "\n".join(chunks) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    styles, scripts = discover_assets()
    outputs = {
        ROOT / "static/css/chartview_release_bundle.css": render(styles, "CSS"),
        ROOT / "static/js/chartview_release_bundle.js": render(scripts, "JavaScript"),
    }
    if args.check:
        stale = [str(path.relative_to(ROOT)) for path, body in outputs.items() if not path.exists() or path.read_text(encoding="utf-8") != body]
        if stale:
            raise SystemExit("stale frontend bundle: " + ", ".join(stale))
        return 0
    for path, body in outputs.items():
        path.write_text(body, encoding="utf-8", newline="\n")
    print(f"Bundled {len(styles)} styles and {len(scripts)} scripts")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
