from __future__ import annotations

import argparse
import hashlib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
JS_OUTPUT = ROOT / "static/js/chartview_boot_bundle.js"
CSS_OUTPUT = ROOT / "static/css/chartview_boot_bundle.css"
TEMPLATE = ROOT / "templates/index.html"

BOOT_SCRIPTS = [
    "static/js/p2_revisit_v1.js",
    "static/js/chart.js",
    "static/js/fwdper.js",
    "static/js/valuation_bands.js",
    "static/js/macro.js",
    "static/js/chartview_release_bundle.js",
    "static/js/live_quotes_v56.js",
    "static/js/visitor_v66.js",
    "static/js/home_heatmap_v57.js",
    "static/js/ux_patch.js",
    "static/js/home_watchlist_boot_v32c.js",
    "static/js/consensus_v2.js",
    "static/js/ai_daily_widget.js",
    "static/js/home_summary_v54.js",
    "static/js/ui_continuity_v53.js",
    "static/js/profile_sync_v1.js",
    "static/js/recommendation_watchlist_v55.js",
    "static/js/promo_v1.js",
]

BOOT_STYLES = [
    "static/css/style.css",
    "static/css/ux_patch.css",
    "static/css/promo_v1.css",
    "static/css/chartview_release_bundle.css",
    "static/css/ui_continuity_v53.css",
    "static/css/live_quotes_v56.css",
    "static/css/home_heatmap_v57.css",
    "static/css/p2_revisit_v1.css",
]

JS_DATA_ATTRS = """data-fast-screener data-valuation-meta data-investment-ideas data-dense-valuation data-revision-radar
        data-investment-tools-v22 data-watchlist-v30 data-watchlist-quick-add-v48 data-ux-v3 data-decision-ux-v7
        data-app-header-v5 data-home-market-v9 data-home-priority-v10 data-ux-patterns-v12 data-ux-interactions-v13
        data-home-ux-v23 data-home-v8 data-app-state-v40 data-single-detail-v40 data-detail-visibility-v401
        data-personalized-news-v40 data-news-status-v401 data-release-ui-v40 data-release-flow-v40
        data-comparison-compact-v401 data-my-hub-v41 data-news-readability-v412 data-resilience-v413
        data-home-polish-v414 data-home-watchlist-compact-v46 data-home-news-cards-v47"""

CSS_DATA_ATTRS = """data-fast-screener data-ideas-ui data-ux-v3 data-investment-tools-v22 data-watchlist-v30
        data-bottom-nav-v6 data-app-states-v32 data-decision-ux-v7 data-app-header-v5 data-home-market-v9
        data-home-priority-v10 data-valuation-matrix-v10 data-ux-patterns-v12 data-ux-interactions-v13
        data-analysis-ui-v20 data-home-ux-v23 data-home-v8 data-personalization-v36 data-personalized-news-v38
        data-home-visual-v39 data-home-visual-v391 data-ui-polish-v392 data-clarity-v393 data-release-ui-v40
        data-detail-ui-v40 data-comparison-ui-v40 data-comparison-compact-v401 data-news-status-v401
        data-my-hub-v41 data-news-readability-v412 data-news-summary-expand-v48 data-resilience-v413
        data-home-polish-v414 data-home-watchlist-compact-v46 data-home-news-cards-v47"""

LEGACY_JS_START = re.compile(r'\s*<script defer src="/static/js/chart\.js\?v=[^"]+"></script>')
LEGACY_JS_END = re.compile(r'<script src="/static/js/p2_revisit_v1\.js\?v=[^"]+"></script>')
LEGACY_CSS_START = re.compile(r'\s*<link rel="stylesheet" href="/static/css/style\.css\?v=[^"]+">')
LEGACY_CSS_END = re.compile(r'<link rel="stylesheet" href="/static/css/p2_revisit_v1\.css\?v=[^"]+">')
RELEASE_JS_REF = re.compile(r'/static/js/chartview_release_bundle\.js\?v=[^"\s]+')
RELEASE_CSS_REF = re.compile(r'/static/css/chartview_release_bundle\.css\?v=[^"\s]+')
AI_REF = re.compile(r'/static/js/ai_daily_widget\.js\?v=[^"\s]+')
BOOT_JS_REF = re.compile(r'/static/js/chartview_boot_bundle\.js\?v=[^"\s]+')
BOOT_CSS_REF = re.compile(r'/static/css/chartview_boot_bundle\.css\?v=[^"\s]+')

def read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8").rstrip()

def render_js_bundle() -> str:
    chunks = [
        "/* ChartView initial boot bundle. Generated by scripts/build_boot_bundle.py. */",
        "window.__CHARTVIEW_BOOT_BUNDLE__ = true;",
    ]
    for path in BOOT_SCRIPTS:
        chunks.append(f"\n/* --- {path} --- */\n{read(path)}\n;")
    return "\n".join(chunks).rstrip() + "\n"

def render_css_bundle() -> str:
    chunks = ["/* ChartView initial CSS bundle. Generated by scripts/build_boot_bundle.py. */"]
    for path in BOOT_STYLES:
        chunks.append(f"\n/* --- {path} --- */\n{read(path)}")
    return "\n".join(chunks).rstrip() + "\n"

def render_template(current: str, js_token: str, css_token: str) -> str:
    release_js = RELEASE_JS_REF.search(current)
    release_css = RELEASE_CSS_REF.search(current)
    ai = AI_REF.search(current)
    if not release_js:
        raise SystemExit("release JS version reference missing")
    if not release_css:
        raise SystemExit("release CSS version reference missing")
    if not ai:
        raise SystemExit("AI widget version reference missing")

    release_js_ref = release_js.group(0)
    release_css_ref = release_css.group(0)
    ai_ref = ai.group(0)

    if BOOT_CSS_REF.search(current):
        current = BOOT_CSS_REF.sub(f"/static/css/chartview_boot_bundle.css?v={css_token}", current, count=1)
    else:
        start = LEGACY_CSS_START.search(current)
        end = LEGACY_CSS_END.search(current)
        if not start or not end or end.end() <= start.start():
            raise SystemExit("legacy CSS block not found")
        css_replacement = f"""
    <!-- Keep one release CSS version reference for the existing generated-bundle verifier. -->
    <meta data-chartview-release-css-version="{release_css_ref}">
    <link rel="stylesheet" href="/static/css/chartview_boot_bundle.css?v={css_token}"
        {CSS_DATA_ATTRS}>"""
        current = current[:start.start()] + css_replacement + current[end.end():]

    if BOOT_JS_REF.search(current):
        current = BOOT_JS_REF.sub(f"/static/js/chartview_boot_bundle.js?v={js_token}", current, count=1)
    else:
        start = LEGACY_JS_START.search(current)
        end = LEGACY_JS_END.search(current)
        if not start or not end or end.end() <= start.start():
            raise SystemExit("legacy JS block not found")
        js_replacement = f"""
    <!-- Keep generated asset version references for the existing verifiers. -->
    <meta data-chartview-release-bundle-version="{release_js_ref}">
    <meta data-ai-daily-widget-version="{ai_ref}">
    <script defer src="/static/js/chartview_boot_bundle.js?v={js_token}"
        {JS_DATA_ATTRS}></script>"""
        current = current[:start.start()] + js_replacement + current[end.end():]

    return current

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    js_bundle = render_js_bundle()
    css_bundle = render_css_bundle()
    js_token = hashlib.sha256(js_bundle.encode("utf-8")).hexdigest()[:12]
    css_token = hashlib.sha256(css_bundle.encode("utf-8")).hexdigest()[:12]
    template = render_template(TEMPLATE.read_text(encoding="utf-8"), js_token, css_token)

    outputs = {
        JS_OUTPUT: js_bundle,
        CSS_OUTPUT: css_bundle,
        TEMPLATE: template,
    }
    stale = [
        str(path.relative_to(ROOT))
        for path, body in outputs.items()
        if not path.exists() or path.read_text(encoding="utf-8") != body
    ]

    if args.check:
        if stale:
            raise SystemExit("stale boot bundle: " + ", ".join(stale))
        print("boot bundles are current")
        return 0

    for path, body in outputs.items():
        path.write_text(body, encoding="utf-8")
    print(f"wrote {JS_OUTPUT.relative_to(ROOT)} ({js_token})")
    print(f"wrote {CSS_OUTPUT.relative_to(ROOT)} ({css_token})")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
