from __future__ import annotations

import argparse
import hashlib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "static/js/chartview_boot_bundle.js"
TEMPLATE = ROOT / "templates/index.html"

BOOT_SCRIPTS = [
    "static/js/p2_revisit_v1.js",
    "static/js/chart.js",
    "static/js/fwdper.js",
    "static/js/valuation_bands.js",
    "static/js/macro.js",
    "static/js/chartview_release_bundle.js",
    "static/js/live_quotes_v56.js",
    "static/js/visitor_v66.js",
    "static/js/home_heatmap_v57.js",
    "static/js/ux_patch.js",
    "static/js/home_watchlist_boot_v32c.js",
    "static/js/consensus_v2.js",
    "static/js/ai_daily_widget.js",
    "static/js/ui_continuity_v53.js",
    "static/js/profile_sync_v1.js",
    "static/js/recommendation_watchlist_v55.js",
    "static/js/promo_v1.js",
]

DATA_ATTRS = """data-fast-screener data-valuation-meta data-investment-ideas data-dense-valuation data-revision-radar
        data-investment-tools-v22 data-watchlist-v30 data-watchlist-quick-add-v48 data-ux-v3 data-decision-ux-v7
        data-app-header-v5 data-home-market-v9 data-home-priority-v10 data-ux-patterns-v12 data-ux-interactions-v13
        data-home-ux-v23 data-home-v8 data-app-state-v40 data-single-detail-v40 data-detail-visibility-v401
        data-personalized-news-v40 data-news-status-v401 data-release-ui-v40 data-release-flow-v40
        data-comparison-compact-v401 data-my-hub-v41 data-news-readability-v412 data-resilience-v413
        data-home-polish-v414 data-home-watchlist-compact-v46 data-home-news-cards-v47"""

LEGACY_START = re.compile(r'\s*<script defer src="/static/js/chart\.js\?v=[^"]+"></script>')
LEGACY_END = re.compile(r'<script src="/static/js/p2_revisit_v1\.js\?v=[^"]+"></script>')
RELEASE_REF = re.compile(r'/static/js/chartview_release_bundle\.js\?v=[^"\s]+')
AI_REF = re.compile(r'/static/js/ai_daily_widget\.js\?v=[^"\s]+')
BOOT_REF = re.compile(r'/static/js/chartview_boot_bundle\.js\?v=[^"\s]+')

def read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8").rstrip()

def render_bundle() -> str:
    chunks = [
        "/* ChartView initial boot bundle. Generated by scripts/build_boot_bundle.py. */",
        "window.__CHARTVIEW_BOOT_BUNDLE__ = true;",
    ]
    for path in BOOT_SCRIPTS:
        chunks.append(f"\n/* --- {path} --- */\n{read(path)}\n;")
    return "\n".join(chunks).rstrip() + "\n"

def render_template(current: str, token: str) -> str:
    release = RELEASE_REF.search(current)
    ai = AI_REF.search(current)
    if not release:
        raise SystemExit("release bundle version reference missing")
    if not ai:
        raise SystemExit("AI widget version reference missing")
    release_ref = release.group(0)
    ai_ref = ai.group(0)

    if BOOT_REF.search(current):
        return BOOT_REF.sub(f"/static/js/chartview_boot_bundle.js?v={token}", current, count=1)

    start = LEGACY_START.search(current)
    end = LEGACY_END.search(current)
    if not start or not end or end.end() <= start.start():
        raise SystemExit("legacy script block not found")

    replacement = f"""
    <!-- Keep one release-bundle version reference for the existing generated-bundle verifier. -->
    <meta data-chartview-release-bundle-version="{release_ref}">
    <meta data-ai-daily-widget-version="{ai_ref}">
    <script defer src="/static/js/chartview_boot_bundle.js?v={token}"
        {DATA_ATTRS}></script>"""
    return current[:start.start()] + replacement + current[end.end():]

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    bundle = render_bundle()
    token = hashlib.sha256(bundle.encode("utf-8")).hexdigest()[:12]
    template = render_template(TEMPLATE.read_text(encoding="utf-8"), token)

    stale = []
    if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != bundle:
        stale.append(str(OUTPUT.relative_to(ROOT)))
    if TEMPLATE.read_text(encoding="utf-8") != template:
        stale.append(str(TEMPLATE.relative_to(ROOT)))

    if args.check:
        if stale:
            raise SystemExit("stale boot bundle: " + ", ".join(stale))
        print("boot bundle is current")
        return 0

    OUTPUT.write_text(bundle, encoding="utf-8")
    TEMPLATE.write_text(template, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({token})")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
