"""Build deterministic critical/deferred release bundles from the legacy asset loaders."""

from __future__ import annotations

import argparse
import hashlib
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LOADERS = (
    ROOT / "static/js/ux_patch.js",
    ROOT / "static/js/ux_v3.js",
    ROOT / "static/js/home_watchlist_boot_v32c.js",
)
EXTRA_ASSETS = (
    ROOT / "static/css/home_brief_v8.css",
    ROOT / "static/js/home_brief_v8.js",
)
ASSET_CALL = re.compile(
    r"(?:ensureStyle|ensureScript|addStyle|addScript)\(\s*'[^']+'\s*,\s*'(?P<path>/static/(?:css|js)/[^'?]+)(?:\?[^']*)?'"
)

# These modules create the shell/Home/primary navigation or are required for
# immediate primary-tab/deep-link behavior. Everything else is loaded after
# first paint from chartview_release_deferred.js.
CRITICAL_SCRIPTS = {
    "static/js/screener.js",
    "static/js/watchlist_v30.js",
    "static/js/ux_v3.js",
    "static/js/app_header_v5.js",
    "static/js/home_market_v9.js",
    "static/js/home_priority_v10.js",
    "static/js/home_ux_v23.js",
    "static/js/app_state_v40.js",
    "static/js/single_detail_v40.js",
    "static/js/detail_visibility_v40_1.js",
    "static/js/release_ui_v40.js",
    "static/js/release_flow_v40.js",
    "static/js/comparison_compact_v40_1.js",
    "static/js/my_hub_v41.js",
    "static/js/resilience_v41_3.js",
    "static/js/home_polish_v41_4.js",
    "static/js/home_watchlist_compact_v46.js",
    "static/js/home_brief_v8.js",
}


def discover_assets() -> tuple[list[Path], list[Path]]:
    styles: list[Path] = []
    scripts: list[Path] = []
    seen: set[Path] = set()
    for loader in LOADERS:
        for match in ASSET_CALL.finditer(loader.read_text(encoding="utf-8")):
            path = ROOT / match.group("path").lstrip("/")
            if path in seen:
                continue
            seen.add(path)
            (styles if path.suffix == ".css" else scripts).append(path)
    for path in EXTRA_ASSETS:
        if path not in seen:
            (styles if path.suffix == ".css" else scripts).append(path)
    return styles, scripts


def render(paths: list[Path], kind: str, *, bundle_flag: bool = False) -> str:
    chunks = [f"/* ChartView {kind} bundle. Generated by scripts/build_frontend_bundle.py. */"]
    is_javascript = kind.endswith("JavaScript")\n    if is_javascript and bundle_flag:
        chunks.append("window.__CHARTVIEW_RELEASE_BUNDLE__ = true;")
    for path in paths:
        relative = path.relative_to(ROOT).as_posix()
        chunks.append(f"\n/* --- {relative} --- */\n{path.read_text(encoding='utf-8').rstrip()}")
        if kind == "JavaScript":
            chunks.append(";")
    return "\n".join(chunks) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    styles, scripts = discover_assets()
    critical = [p for p in scripts if p.relative_to(ROOT).as_posix() in CRITICAL_SCRIPTS]
    deferred = [p for p in scripts if p.relative_to(ROOT).as_posix() not in CRITICAL_SCRIPTS]
    missing = sorted(CRITICAL_SCRIPTS - {p.relative_to(ROOT).as_posix() for p in scripts})
    if missing:
        raise SystemExit("critical frontend modules not discovered: " + ", ".join(missing))

    outputs = {
        ROOT / "static/css/chartview_release_bundle.css": render(styles, "CSS"),
        ROOT / "static/js/chartview_release_bundle.js": render(critical, "JavaScript", bundle_flag=True),
        ROOT / "static/js/chartview_release_deferred.js": render(deferred, "Deferred JavaScript"),
    }
    template = ROOT / "templates/index.html"
    html = template.read_text(encoding="utf-8")
    versioned = {
        **outputs,
        ROOT / "static/js/ai_daily_widget.js": (ROOT / "static/js/ai_daily_widget.js").read_text(encoding="utf-8"),
    }
    for path, body in versioned.items():
        token = hashlib.sha256(body.encode("utf-8")).hexdigest()[:12]
        asset = path.relative_to(ROOT).as_posix()
        html, count = re.subn(rf'/{re.escape(asset)}\?v=[^"\s]+', f'/{asset}?v={token}', html)
        if count != 1:
            raise SystemExit(f"Expected exactly one template reference: {asset}, got {count}")
    outputs[template] = html

    if args.check:
        stale = [
            str(path.relative_to(ROOT))
            for path, body in outputs.items()
            if not path.exists() or path.read_text(encoding="utf-8") != body
        ]
        if stale:
            raise SystemExit("stale frontend bundle: " + ", ".join(stale))
        return 0

    for path, body in outputs.items():
        path.write_text(body, encoding="utf-8", newline="\n")
    print(
        f"Bundled {len(styles)} styles, {len(critical)} critical scripts, "
        f"{len(deferred)} deferred scripts"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
